[package]
name = "blast"
version = "0.1.0"
authors = ["pheneg1 <paul-andre.henegar@mail.mcgill.ca>"]

[dependencies]
websocket = "0.20"
rand = "0.4"
byteorder = "1"
chan = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
